version: '3.8'
services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: cinema_app
      POSTGRES_PASSWORD: cinema_app
      POSTGRES_DB: cinema_app
    ports:
      - "25432:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
  # app:
  #   build:
  #     context: .
  #     target: dev
  #   ports:
  #     - '5000:5000'
  #   volumes:
  #     - .:/app:delegated
  #   environment:
  #     NODE_ENV: development
